name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test on iOS Simulator
    runs-on: macos-latest
    env:
      XCODE_PROJECT: "HackerTube.xcodeproj"
      SCHEME: "HackerTube"
      PLATFORM: 'iOS Simulator'
      DEVICE: 'iPhone 16'
      TEST_PLAN: UnitTests
      TEST_RESULT_BUNDLE: "TestResults.xcresult"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Test
        run: |
          set -o pipefail && xcodebuild test \
            -project "${{ env.XCODE_PROJECT }}" \
            -scheme ${{ env.SCHEME }} \
            -testPlan "${{ env.TEST_PLAN }}" \
            -resultBundlePath "${{ env.TEST_RESULT_BUNDLE }}" \
            -destination "platform=${{ env.PLATFORM }},name=${{ env.DEVICE }}" | xcpretty

      - name: Upload test result bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SCHEME }}-${{ github.sha }}.xcresult
          path: ${{ env.TEST_RESULT_BUNDLE }}
